terminal:
  # This can be any image that has the necessary runtime environment for your project.
  image: golang:latest
  before_script:
    - apk update
  script: sleep 20
  variables:
    GOP_ENV: "test"
